# Generated by Django 5.1.6 on 2025-02-14 18:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit_type', models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilograms')], max_length=3)),
                ('category', models.CharField(choices=[('groceries', 'Groceries'), ('entertainment', 'Entertainment'), ('clothing', 'Clothing'), ('electronics', 'Electronics'), ('transport', 'Transport'), ('health', 'Health'), ('other', 'Other')], default='other', max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('manufacturer_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'indexes': [models.Index(fields=['name', 'brand', 'unit_type'], name='expenses_pu_name_5c4e81_idx'), models.Index(fields=['category'], name='expenses_pu_categor_c981ea_idx'), models.Index(fields=['created_at'], name='expenses_pu_created_89a604_idx')],
                'unique_together': {('name', 'brand', 'unit_type')},
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('store_name', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('calculate_total', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receipts',
                'verbose_name_plural': 'Receipt',
            },
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_items', to='expenses.purchase')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='expenses.receipt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receipt Items',
                'verbose_name_plural': 'Receipt Item',
            },
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_items',
            field=models.ManyToManyField(blank='True', related_name='receipts', through='expenses.ReceiptItem', to='expenses.purchase'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calculate_total', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('receipts', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='expenses.receipt')),
            ],
            options={
                'verbose_name': 'Expenses',
                'verbose_name_plural': 'Expense',
                'indexes': [models.Index(fields=['date'], name='expenses_ex_date_17a2b2_idx'), models.Index(fields=['user'], name='expenses_ex_user_id_51d8ba_idx'), models.Index(fields=['created_at'], name='expenses_ex_created_52941d_idx'), models.Index(fields=['user', 'date'], name='expenses_ex_user_id_713a9d_idx'), models.Index(fields=['total_amount'], name='expenses_ex_total_a_0dff09_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='receiptitem',
            index=models.Index(fields=['purchase'], name='expenses_re_purchas_e54509_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptitem',
            index=models.Index(fields=['user'], name='expenses_re_user_id_760b9c_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptitem',
            index=models.Index(fields=['unit_price'], name='expenses_re_unit_pr_59b149_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptitem',
            index=models.Index(fields=['purchase', 'user'], name='expenses_re_purchas_d04709_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['date'], name='expenses_re_date_6ca0df_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['user'], name='expenses_re_user_id_d60e16_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['created_at'], name='expenses_re_created_a22d14_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['user', 'date'], name='expenses_re_user_id_70be80_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['user', 'store_name'], name='expenses_re_user_id_f473db_idx'),
        ),
    ]
