# Generated by Django 5.1.6 on 2025-02-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_receipts_alter_expense_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='expense',
            name='receipts',
        ),
        migrations.AddField(
            model_name='expense',
            name='receipts',
            field=models.ManyToManyField(blank=True, related_name='expense', to='expenses.receipt'),
        ),
    ]
