# Generated by Django 5.1.6 on 2025-02-17 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_expense_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='receipts',
        ),
        migrations.AddField(
            model_name='receipt',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='expenses.expense'),
        ),
    ]
